### ISSUE TITLE
Cannot login on Linux

### ISSUE THREAD

**Issue by DannyGrey7** [vrchatapi/VRChatPython#31]
It was able to log into VRC when testing on Windows 10. But when I run it on my Raspberry Pi, I got an "IntegretyError:CurrentUser object missing required key username" despite having a username,

`Traceback (most recent call last):
  File "/home/pi/CheetoBot/cogs/vrchat.py", line 41, in connectVRC
    await self.vrcclient.login(
  File "/home/pi/.local/lib/python3.9/site-packages/vrcpy/client.py", line 383, in login
    self.me = CurrentUser(self, resp["data"], self.loop)
  File "/home/pi/.local/lib/python3.9/site-packages/vrcpy/user.py", line 382, in __init__
    self._assign(obj)
  File "/home/pi/.local/lib/python3.9/site-packages/vrcpy/baseobject.py", line 27, in _assign
    self._object_integrety(obj)
  File "/home/pi/.local/lib/python3.9/site-packages/vrcpy/baseobject.py", line 91, in _object_integrety
    raise ObjectErrors.IntegretyError(
vrcpy.errors.ObjectErrors.IntegretyError: CurrentUser object missing required key username`

Python Version: 3.9.6
Platform: Linux-5.10.17-v7+-armv7l-with-glibc2.28

**Comment by Katistic** [comment]
I've recently redone the core request class of vrcpy and it doesn't have all the correct exceptions yet. Whats likely happened is you've got your login details incorrect or your mfa wrong

**Comment by Katistic** [comment]
It doesn't catch the 401/403 so it passes unexpected json to the CurrentUser class, resulting in the raised IntegretyError

**Comment by DannyGrey7** [comment]
Actually, you're right. I got my login details wrong and it finally logged in after correcting it. Thanks for your help!
